apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    app: httpd-frontend
    tier: frontend
spec:
  selector:
    matchLabels:
        app: httpd-frontend
  
  template: 
    metadata:
      name: httpd-frontend
      labels:
        app: httpd-frontend
        tier: frontend
    spec:
      containers:
        - name: httpd-frontend
          image: httpd:2.4-alpine
  replicas: 3